skip = [
  # Can't build monorepos
  "https://github.com/zed-industries/zed",

  # Invalid extension.toml
  "https://github.com/hasit/zed-fish",
  "https://github.com/sonodima/zed-mellow",

  # Missing extension.toml
  "https://github.com/Brunowilliang/zedspace",
  "https://github.com/DanielMSchmidt/zed-synthwave",
  "https://github.com/DevBlocky/zed-asm",
  "https://github.com/Fastiraz/nanowise",
  "https://github.com/Feel-ix-343/markdown-oxide",
  "https://github.com/ThomasAlban/everforest-zed",
  "https://github.com/arifzeeshan/Muted",
  "https://github.com/blopker/codebook",
  "https://github.com/d1y/vscode-monokaicharcoal.zed",
  "https://github.com/d1y/vscode_dark_plus.zed",
  "https://github.com/daltonmenezes/aura-theme",
  "https://github.com/distributed-intelligence/warp-one-dark",
  "https://github.com/elGusto/night-owlz",
  "https://github.com/euyogi/Tema-YogiAmoled",
  "https://github.com/fiberplane/fpx",
  "https://github.com/joshrutkowski/zed-smithy",
  "https://github.com/kwonoj/zed-blanche",
  "https://github.com/mantou132/gem",
  "https://github.com/miguelsolorio/vscode-symbols",
  "https://github.com/napalmpapalam/napalm-theme-zed",
  "https://github.com/p3rception/Indigo-zed",
  "https://github.com/posit-dev/air",
  "https://github.com/rzukic/zed-matlab",
  "https://github.com/skarline/zed-fleet-themes",
  "https://github.com/srcery-colors/srcery-zed",
  "https://github.com/syntaxfm/syntax-zed-theme",
  "https://github.com/teziovsky/zed-one-hunter-theme",
  "https://github.com/webhooked/asteroid-zed",
  "https://github.com/webhooked/norrsken-zed",
  "https://github.com/webhooked/vintergata-zed",

  # Missing Cargo.lock
  "https://github.com/4teapo/zed-luau",
  "https://github.com/AineeJames/c3-zed",
  "https://github.com/BaptisteRoseau/zed-typos",
  "https://github.com/DavidLee18/zed_norminette",
  "https://github.com/DavidZwitser/zed-bqn",
  "https://github.com/FyraLabs/zed-vala",
  "https://github.com/StyraInc/zed-rego",
  "https://github.com/Xavier-Maruff/zed-fortran",
  "https://github.com/anikinmd/zed_bitbake",
  "https://github.com/anikinmd/zed_devicetree",
  "https://github.com/cabrinha/helm.zed",
  "https://github.com/elmarco/zed-rst",
  "https://github.com/foxoman/zed-nim",
  "https://github.com/grndctrl/zed-gdscript",
  "https://github.com/gvozdvmozgu/sqruff-zed/",
  "https://github.com/h2000/zed-roc",
  "https://github.com/hqnna/zed-meson",
  "https://github.com/iwe-org/zed-iwe",
  "https://github.com/janezpodhostnik/cadence.zed",
  "https://github.com/k0tran/zed_neocmake",
  "https://github.com/kadena-community/pact-zed",
  "https://github.com/luan/zed-wgsl",
  "https://github.com/lv37/zed-v",
  "https://github.com/m1guer/basedpyright-zed",
  "https://github.com/makifdb/zed-templ",
  "https://github.com/mantou132/zed-cspell",
  "https://github.com/nusnewob/caddyfile-zed",
  "https://github.com/oWretch/zed-extension-bicep",
  "https://github.com/ocsmit/zed-r",
  "https://github.com/rowillia/zed-python-refactoring",
  "https://github.com/rxptr/zed-odin",
  "https://github.com/sachk/aw-watcher-zed",
  "https://github.com/scalameta/metals-zed",
  "https://github.com/staysail/zed-d",
  "https://github.com/stef16robbe/harper_zed",
  "https://github.com/tfuxu/zed-blueprint",
  "https://github.com/zed-extensions/java",

  # Repository does not exist
  "https://codeberg.org/mattly/zed-lang-fennel",
  "https://github.com/Fake-User/Struct-Zed-Theme",
  "https://github.com/LightTreasure/zed-axolosin-theme",
  "https://github.com/andreicek/asciidoc-zed",
  "https://github.com/aripiprazole/unicode",
  "https://github.com/lohazo/solarized-fp",
  "https://github.com/michaelandreuzza/malibu-theme-zed",
  "https://github.com/piefayth/prolog",
  "https://github.com/rushabhcodes/zed-chia-theme",
  "https://github.com/your-name/my-zed-extension",
]
