name: Test

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            nixpkgs: github:NixOS/nixpkgs/nixos-25.11

          - runner: ubuntu-24.04
            nixpkgs: github:NixOS/nixpkgs/nixpkgs-unstable

          - runner: ubuntu-24.04-arm
            nixpkgs: github:NixOS/nixpkgs/nixos-25.11

          - runner: ubuntu-24.04-arm
            nixpkgs: github:NixOS/nixpkgs/nixpkgs-unstable

          - runner: macos-14
            nixpkgs: github:NixOS/nixpkgs/nixos-25.11

          - runner: macos-14
            nixpkgs: github:NixOS/nixpkgs/nixpkgs-unstable
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34

      - name: Test
        env:
          NIXPKGS: ${{ matrix.nixpkgs }}
        shell: nix develop --command bash {0}
        run: ./scripts/test.sh "${NIXPKGS}"
